///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Trendyol_Test_Automation_with_Ranorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording2 recording.
    /// </summary>
    [TestModule("9b49c894-a359-4a64-bb84-211a1bf3bc0a", ModuleType.Recording, 1)]
    public partial class Recording2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Trendyol_Test_Automation_with_RanorexRepository repository.
        /// </summary>
        public static Trendyol_Test_Automation_with_RanorexRepository repo = Trendyol_Test_Automation_with_RanorexRepository.Instance;

        static Recording2 instance = new Recording2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl' at 36;9.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOlInfo, new RecordItemIndex(0));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl.Click("36;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=333,Height=42}) on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.ErrorBoxWrapper'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.ErrorBoxWrapperInfo, new RecordItemIndex(1));
            Validate.CompareImage(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.ErrorBoxWrapperInfo, ErrorBoxWrapper_Screenshot1, ErrorBoxWrapper_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterEmail' at 135;21.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterEmailInfo, new RecordItemIndex(2));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterEmail.Click("135;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'trendyolranorex@gmail.com' with focus on 'EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterEmail'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterEmailInfo, new RecordItemIndex(3));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterEmail.PressKeys("trendyolranorex@gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl' at 17;4.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOlInfo, new RecordItemIndex(4));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl.Click("17;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(5));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=333,Height=42}) on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.ErrorBoxWrapper'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.ErrorBoxWrapperInfo, new RecordItemIndex(6));
            Validate.CompareImage(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.ErrorBoxWrapperInfo, ErrorBoxWrapper_Screenshot1_2, ErrorBoxWrapper_Screenshot1_2_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(7));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterPasswordInput' at 149;14.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterPasswordInputInfo, new RecordItemIndex(8));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterPasswordInput.Click("149;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'trendyol12345!' with focus on 'EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterPasswordInput'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterPasswordInputInfo, new RecordItemIndex(9));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterPasswordInput.PressKeys("trendyol12345!");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl' at 31;3.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOlInfo, new RecordItemIndex(10));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl.Click("31;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlex1'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlex1Info, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlex1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=333,Height=34}) on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlex1'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlex1Info, new RecordItemIndex(12));
            Validate.CompareImage(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlex1Info, TyCheckboxWrapperTyDisplayFlex1_Screenshot1, TyCheckboxWrapperTyDisplayFlex1_Screenshot1_Options);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage ErrorBoxWrapper_Screenshot1
        { get { return repo.EnTrendUEruenlerTuerkiyeninOnlineAl.ErrorBoxWrapperInfo.GetScreenshot1(new Rectangle(0, 0, 333, 42)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions ErrorBoxWrapper_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,333,42;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage ErrorBoxWrapper_Screenshot1_2
        { get { return repo.EnTrendUEruenlerTuerkiyeninOnlineAl.ErrorBoxWrapperInfo.GetScreenshot1(new Rectangle(0, 0, 333, 42)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions ErrorBoxWrapper_Screenshot1_2_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,333,42;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage TyCheckboxWrapperTyDisplayFlex1_Screenshot1
        { get { return repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlex1Info.GetScreenshot1(new Rectangle(0, 0, 333, 34)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions TyCheckboxWrapperTyDisplayFlex1_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,333,34;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
