///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Trendyol_Test_Automation_with_Ranorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording6 recording.
    /// </summary>
    [TestModule("6b1869d9-fdbd-4dd0-8f68-98589ff8b099", ModuleType.Recording, 1)]
    public partial class Recording6 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Trendyol_Test_Automation_with_RanorexRepository repository.
        /// </summary>
        public static Trendyol_Test_Automation_with_RanorexRepository repo = Trendyol_Test_Automation_with_RanorexRepository.Instance;

        static Recording6 instance = new Recording6();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording6()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording6 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Sepetim' at 34;4.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.SepetimInfo, new RecordItemIndex(0));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Sepetim.Click("34;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.SepetiOnayla' at 68;13.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.SepetiOnaylaInfo, new RecordItemIndex(1));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.SepetiOnayla.Click("68;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComSepetimOdeme'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComSepetimOdemeInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComSepetimOdemeInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComSepetimOdeme'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComSepetimOdemeInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComSepetimOdemeInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
