///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Trendyol_Test_Automation_with_Ranorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording4 recording.
    /// </summary>
    [TestModule("93d49156-bb10-46c6-96f4-205154b68186", ModuleType.Recording, 1)]
    public partial class Recording4 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Trendyol_Test_Automation_with_RanorexRepository repository.
        /// </summary>
        public static Trendyol_Test_Automation_with_RanorexRepository repo = Trendyol_Test_Automation_with_RanorexRepository.Instance;

        static Recording4 instance = new Recording4();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording4()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording4 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.GirişYap' at 21;4.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.GirişYapInfo, new RecordItemIndex(0));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.GirişYap.Click("21;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl' at 590;370.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.SelfInfo, new RecordItemIndex(1));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Self.Click("590;370");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'trendyoleranorex@hotmail.com' with focus on 'EnTrendUEruenlerTuerkiyeninOnlineAl'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.SelfInfo, new RecordItemIndex(2));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Self.EnsureVisible();
            Keyboard.Press("trendyoleranorex@hotmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.LoginPasswordInput' at 75;14.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.LoginPasswordInputInfo, new RecordItemIndex(3));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.LoginPasswordInput.Click("75;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'trendyol1234!' with focus on 'EnTrendUEruenlerTuerkiyeninOnlineAl.LoginPasswordInput'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.LoginPasswordInputInfo, new RecordItemIndex(4));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.LoginPasswordInput.PressKeys("trendyol1234!");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.GirişYap1' at 22;1.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.GirişYap1Info, new RecordItemIndex(5));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.GirişYap1.Click("22;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(6));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(11210);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'EnTrendUEruenlerTuerkiyeninOnlineAl.DivTag5750TL' at 52;1.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.DivTag5750TLInfo, new RecordItemIndex(7));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.DivTag5750TL.MoveTo("52;1");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'EnTrendUEruenlerTuerkiyeninOnlineAl.SomeDivTag' at 755;404.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.SomeDivTagInfo, new RecordItemIndex(8));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.SomeDivTag.MoveTo("755;404");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(27020);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'EnTrendUEruenlerTuerkiyeninOnlineAl.SepeteEkle' at 290;13.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.SepeteEkleInfo, new RecordItemIndex(9));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.SepeteEkle.MoveTo("290;13");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComSepet'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComSepetInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComSepetInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
