///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Trendyol_Test_Automation_with_Ranorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("e2c13d4f-c819-4978-9682-12906fe4e898", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Trendyol_Test_Automation_with_RanorexRepository repository.
        /// </summary>
        public static Trendyol_Test_Automation_with_RanorexRepository repo = Trendyol_Test_Automation_with_RanorexRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.GirişYap' at 27;6.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.GirişYapInfo, new RecordItemIndex(0));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.GirişYap.Click("27;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.ButtonQButtonQButtonMediumQSecond' at 76;18.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.ButtonQButtonQButtonMediumQSecondInfo, new RecordItemIndex(1));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.ButtonQButtonQButtonMediumQSecond.Click("76;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.EmailInputQInputWrapper'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.EmailInputQInputWrapperInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.EmailInputQInputWrapperInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.EmailInputQInputWrapper'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.EmailInputQInputWrapperInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.EmailInputQInputWrapperInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QInputWrapper'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QInputWrapperInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QInputWrapperInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QInputWrapper'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QInputWrapperInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QInputWrapperInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.FlexFlexColumnGender'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.FlexFlexColumnGenderInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.FlexFlexColumnGenderInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.FlexFlexColumnGender'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.FlexFlexColumnGenderInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.FlexFlexColumnGenderInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(8));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrima'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrimaInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrimaInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrima'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrimaInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrimaInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlex'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlexInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlexInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlex'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlexInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlexInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlex1'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlex1Info, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlex1Info, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlex1'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlex1Info, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.TyCheckboxWrapperTyDisplayFlex1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.FlexFlex1QLayoutSocialLoginButton'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.FlexFlex1QLayoutSocialLoginButtonInfo, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.FlexFlex1QLayoutSocialLoginButtonInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.FlexFlex1QLayoutSocialLoginButton'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.FlexFlex1QLayoutSocialLoginButtonInfo, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.FlexFlex1QLayoutSocialLoginButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.FlexFlex1QLayoutSocialLoginButton1'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.FlexFlex1QLayoutSocialLoginButton1Info, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.FlexFlex1QLayoutSocialLoginButton1Info, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.FlexFlex1QLayoutSocialLoginButton1'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.FlexFlex1QLayoutSocialLoginButton1Info, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.FlexFlex1QLayoutSocialLoginButton1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
