///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Trendyol_Test_Automation_with_Ranorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Trendyol_Test_Automation_with_RanorexRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("49cdbdd9-4eb7-4762-adb1-c06462abc593")]
    public partial class Trendyol_Test_Automation_with_RanorexRepository : RepoGenBaseFolder
    {
        static Trendyol_Test_Automation_with_RanorexRepository instance = new Trendyol_Test_Automation_with_RanorexRepository();
        Trendyol_Test_Automation_with_RanorexRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder _entrendueruenlertuerkiyeninonlineal;
        Trendyol_Test_Automation_with_RanorexRepositoryFolders.SepetimTrendyolGoogleChromeAppFolder _sepetimtrendyolgooglechrome;

        /// <summary>
        /// Gets the singleton class instance representing the Trendyol_Test_Automation_with_RanorexRepository element repository.
        /// </summary>
        [RepositoryFolder("49cdbdd9-4eb7-4762-adb1-c06462abc593")]
        public static Trendyol_Test_Automation_with_RanorexRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Trendyol_Test_Automation_with_RanorexRepository() 
            : base("Trendyol_Test_Automation_with_RanorexRepository", "/", null, 0, false, "49cdbdd9-4eb7-4762-adb1-c06462abc593", ".\\RepositoryImages\\Trendyol_Test_Automation_with_RanorexRepository49cdbdd9.rximgres")
        {
            _entrendueruenlertuerkiyeninonlineal = new Trendyol_Test_Automation_with_RanorexRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder(this);
            _sepetimtrendyolgooglechrome = new Trendyol_Test_Automation_with_RanorexRepositoryFolders.SepetimTrendyolGoogleChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("49cdbdd9-4eb7-4762-adb1-c06462abc593")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAl folder.
        /// </summary>
        [RepositoryFolder("72d1d465-7615-402a-af79-0110036102ee")]
        public virtual Trendyol_Test_Automation_with_RanorexRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder EnTrendUEruenlerTuerkiyeninOnlineAl
        {
            get { return _entrendueruenlertuerkiyeninonlineal; }
        }

        /// <summary>
        /// The SepetimTrendyolGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("526bc77a-1dc7-4a3d-8fb3-d10fe773818e")]
        public virtual Trendyol_Test_Automation_with_RanorexRepositoryFolders.SepetimTrendyolGoogleChromeAppFolder SepetimTrendyolGoogleChrome
        {
            get { return _sepetimtrendyolgooglechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Trendyol_Test_Automation_with_RanorexRepositoryFolders
    {
        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder folder.
        /// </summary>
        [RepositoryFolder("72d1d465-7615-402a-af79-0110036102ee")]
        public partial class EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder : RepoGenBaseFolder
        {
            Trendyol_Test_Automation_with_RanorexRepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsFolder _httpswwwtrendyolcomuyelikcbeqhttps;
            RepoItemInfo _ueyeolInfo;
            RepoItemInfo _flexflex1qlayoutsocialloginbuttonInfo;
            RepoItemInfo _flexflex1qlayoutsocialloginbutton1Info;
            RepoItemInfo _girişyapInfo;
            RepoItemInfo _buttonqbuttonqbuttonmediumqsecondInfo;
            ErrorBoxWrapperInfoClass _errorboxwrapperInfo;
            RepoItemInfo _registeremailInfo;
            RepoItemInfo _registerpasswordinputInfo;
            RepoItemInfo _epostaveşifrenizigirinizInfo;
            RepoItemInfo _luetfengecerlibiremailadresigirinizInfo;
            RepoItemInfo _loginpasswordinputInfo;
            RepoItemInfo _girişyap1Info;
            RepoItemInfo _ueyeol1Info;
            RepoItemInfo _ueyeol2Info;
            RepoItemInfo _customstampboxwrapperInfo;
            RepoItemInfo _customstampboxwrapper1Info;
            RepoItemInfo _divtag5750tlInfo;
            RepoItemInfo _somedivtagInfo;
            RepoItemInfo _sepeteekleInfo;
            RepoItemInfo _httpswwwtrendyolcomsepetInfo;
            RepoItemInfo _iheartInfo;
            RepoItemInfo _favorilerimInfo;
            RepoItemInfo _sepetimInfo;
            RepoItemInfo _sepetionaylaInfo;
            RepoItemInfo _httpswwwtrendyolcomsepetimodemeInfo;

            /// <summary>
            /// Creates a new EnTrendUEruenlerTuerkiyeninOnlineAl  folder.
            /// </summary>
            public EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EnTrendUEruenlerTuerkiyeninOnlineAl", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "72d1d465-7615-402a-af79-0110036102ee", "")
            {
                _httpswwwtrendyolcomuyelikcbeqhttps = new Trendyol_Test_Automation_with_RanorexRepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsFolder(this);
                _ueyeolInfo = new RepoItemInfo(this, "UEyeOl", ".//div[#'account-navigation-container']/div/div[1]//div[@innertext='Üye Ol']", ".//div[#'account-navigation-container']//div[@innertext='Üye Ol']", 30000, null, "bfed9282-4c14-4956-9888-e20e00d441fc");
                _flexflex1qlayoutsocialloginbuttonInfo = new RepoItemInfo(this, "FlexFlex1QLayoutSocialLoginButton", ".//div[#'login-register']/div[3]/div[2]/div[1]", ".//div[#'login-register']/div[3]/div[2]/div[1]", 30000, null, "2aa8960d-ca50-4be5-b842-1a244a0671fb");
                _flexflex1qlayoutsocialloginbutton1Info = new RepoItemInfo(this, "FlexFlex1QLayoutSocialLoginButton1", ".//div[#'login-register']/div[3]/div[2]/div[2]", ".//div[#'login-register']/div[3]/div[2]/div[2]", 30000, null, "aa0cd8db-03f2-4294-8559-edf19b685f61");
                _girişyapInfo = new RepoItemInfo(this, "GirişYap", ".//div[#'account-navigation-container']/div/div[1]/?/?/p[@innertext='Giriş Yap']", ".//div[#'account-navigation-container']//p[@innertext='Giriş Yap']", 30000, null, "56c68d7b-0bec-4491-9ceb-dd60db254b2e");
                _buttonqbuttonqbuttonmediumqsecondInfo = new RepoItemInfo(this, "ButtonQButtonQButtonMediumQSecond", ".//div[#'login-register']/div[2]/div/button[2]", ".//div[#'login-register']/div[2]/div/button[2]", 30000, null, "02bbde3e-ba19-418c-a5be-7a2398e16bfd");
                _errorboxwrapperInfo = new ErrorBoxWrapperInfoClass(this);
                _registeremailInfo = new RepoItemInfo(this, "RegisterEmail", ".//input[#'register-email']", ".//input[#'register-email']", 30000, null, "0e790ea7-3706-478f-a88a-f21a46400003");
                _registerpasswordinputInfo = new RepoItemInfo(this, "RegisterPasswordInput", ".//input[#'register-password-input']", ".//input[#'register-password-input']", 30000, null, "2f88602c-8480-4c22-a188-4894233d73ed");
                _epostaveşifrenizigirinizInfo = new RepoItemInfo(this, "EPostaVeŞifreniziGiriniz", ".//div[#'error-box-wrapper']/span[@innertext>'E-posta ve şifrenizi giri']", ".//div[#'error-box-wrapper']/span[@innertext>'E-posta ve şifrenizi giri']", 30000, null, "e7044e87-7ef7-4105-91f3-62e798ccc2b6");
                _luetfengecerlibiremailadresigirinizInfo = new RepoItemInfo(this, "LuetfenGecerliBirEmailAdresiGiriniz", ".//div[#'error-box-wrapper']/span[@innertext>'Lütfen geçerli bir email adresi']", ".//div[#'error-box-wrapper']/span[@innertext>'Lütfen geçerli bir email adresi']", 30000, null, "eac2fc1f-5fd0-4b63-8591-dc98f8652c72");
                _loginpasswordinputInfo = new RepoItemInfo(this, "LoginPasswordInput", ".//input[#'login-password-input']", ".//input[#'login-password-input']", 30000, null, "d770c39c-2eb7-4f77-99de-b548bd346eb1");
                _girişyap1Info = new RepoItemInfo(this, "GirişYap1", ".//div[#'login-register']//form[@action='https://www.trendyol.com/giris?cb=https%3A%2F%2Fwww.trendyol.com%2F']/?/?/span[@innertext='Giriş Yap']", ".//div[#'login-register']//form/button/span[@innertext='Giriş Yap']", 30000, null, "a4f19d55-db5e-41d5-bd0a-dea7713fbdc4");
                _ueyeol1Info = new RepoItemInfo(this, "UEyeOl1", ".//div[#'login-register']/div[2]/div/button[2]/span[@innertext='Üye Ol']", ".//div[#'login-register']//span[@innertext='Üye Ol']", 30000, null, "abb9087b-cc3f-4f4b-98e2-5309fa131b96");
                _ueyeol2Info = new RepoItemInfo(this, "UEyeOl2", ".//div[#'login-register']//span[@innertext='Üye Ol']", ".//div[#'login-register']//span[@innertext='Üye Ol']", 30000, null, "0276f16e-9809-4748-adc3-72808937c0d5");
                _customstampboxwrapperInfo = new RepoItemInfo(this, "CustomStampBoxWrapper", ".//div[#'browsing-gw-homepage']/div/div/div/article[9]/div/div/div[3]/div[2]/div[@title>'Erkek Çocuk Çok Renkli 6''Lı']/a[@href>'https://www.trendyol.com/']/div[1]/div/div[2]", ".//div[#'browsing-gw-homepage']//div[3]/a[@href>'https://www.trendyol.com/']/div[1]/div/div[2]", 30000, null, "d2fb041f-c76a-4dd6-ae8b-11cfd1c6c53e");
                _customstampboxwrapper1Info = new RepoItemInfo(this, "CustomStampBoxWrapper1", ".//div[#'browsing-gw-homepage']/div/div/div/article[6]/div/div/div[3]/div[2]/div[@title='League Of Legends 850 Rp']/a[@href>'https://www.trendyol.com/']/div[1]/div/div[2]", ".//div[#'browsing-gw-homepage']//div[@title='League Of Legends 850 Rp']/a[@href>'https://www.trendyol.com/']/div[1]/div/div[2]", 30000, null, "161a32fb-cd11-4c7a-9716-2739d10f3f5d");
                _divtag5750tlInfo = new RepoItemInfo(this, "DivTag5750TL", ".//div[#'browsing-gw-homepage']/div/div/div/article[6]/div/div/div[3]/div[3]/div[@title='League Of Legends 850 Rp']/a[@href>'https://www.trendyol.com/']/div[2]/div[3]/?/?/div[@innertext='57,50TL']", ".//div[#'browsing-gw-homepage']//div", 30000, null, "816fec75-dca5-43b7-8ab2-fcee14df90fa");
                _somedivtagInfo = new RepoItemInfo(this, "SomeDivTag", "body/?/?/div/div/div/div/div/div/article//div/?/?/div", "body/div/div/div/div/div/div/div/article/div/div/div/div/div/a/div/div/div/div", 30000, null, "81285153-15e9-44cb-b070-a6e215cb38de");
                _sepeteekleInfo = new RepoItemInfo(this, "SepeteEkle", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[2]/div[6]/button/div[@innertext='Sepete Ekle']", ".//main[#'product-detail-app']//div[@innertext='Sepete Ekle']", 30000, null, "dc8bff9e-a44b-448c-a4c9-39459bb99711");
                _httpswwwtrendyolcomsepetInfo = new RepoItemInfo(this, "HttpsWwwTrendyolComSepet", ".//div[#'account-navigation-container']/div/div[2]/a[@href>'https://www.trendyol.com/']", ".//div[#'account-navigation-container']/div/div[2]/a[@href>'https://www.trendyol.com/']", 30000, null, "fd03de0d-9e25-457f-8c33-e1dae0d017a1");
                _iheartInfo = new RepoItemInfo(this, "IHeart", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[2]/div[6]/div/div/div[1]/button/i", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[2]/div[6]/div/div/div[1]/button/i", 30000, null, "6ee7c8f0-7114-4f28-8568-578c6c6c4532");
                _favorilerimInfo = new RepoItemInfo(this, "Favorilerim", ".//div[#'account-navigation-container']/div/a[@href>'https://www.trendyol.com/']/?/?/p[@innertext='Favorilerim']", ".//div[#'account-navigation-container']//p[@innertext='Favorilerim']", 30000, null, "25869f25-39b7-490e-ad31-4457ca968de0");
                _sepetimInfo = new RepoItemInfo(this, "Sepetim", ".//div[#'account-navigation-container']/div/div[2]/a[@href>'https://www.trendyol.com/']/p[@innertext='Sepetim']", ".//div[#'account-navigation-container']//p[@innertext='Sepetim']", 30000, null, "14b26e46-3f5b-42ea-a360-7ba6b2b6fd44");
                _sepetionaylaInfo = new RepoItemInfo(this, "SepetiOnayla", ".//div[#'pb-container']/aside/div/div[4]/?/?/span[@innertext='Sepeti Onayla']", ".//div[#'pb-container']/aside/div/div[4]/a[@href>'https://www.trendyol.com/']/span[@innertext='Sepeti Onayla']", 30000, null, "21d6696c-5842-4caf-a748-eaf69d5be624");
                _httpswwwtrendyolcomsepetimodemeInfo = new RepoItemInfo(this, "HttpsWwwTrendyolComSepetimOdeme", ".//div[#'pb-container']/aside/div/div[4]/a[@href>'https://www.trendyol.com/']", ".//div[#'pb-container']/aside/div/div[4]/a[@href>'https://www.trendyol.com/']", 30000, null, "5816910f-baee-4af8-9db0-8ad3cb7b4050");
            }

            /// <summary>
            /// The ErrorBoxWrapperInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("bf36e58c-1ed0-4455-ab21-eab16f862515")]
            public class ErrorBoxWrapperInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ErrorBoxWrapperInfoClass class constructor.
                /// </summary>
                public ErrorBoxWrapperInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ErrorBoxWrapper", ".//div[#'error-box-wrapper']", 30000, null, "bf36e58c-1ed0-4455-ab21-eab16f862515")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("e5adc2f8-f6c9-4c1e-a5df-0f346cfd6086")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("e5adc2f8-f6c9-4c1e-a5df-0f346cfd6086");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e5adc2f8-f6c9-4c1e-a5df-0f346cfd6086")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e5adc2f8-f6c9-4c1e-a5df-0f346cfd6086", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("72d1d465-7615-402a-af79-0110036102ee")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("72d1d465-7615-402a-af79-0110036102ee")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UEyeOl item.
            /// </summary>
            [RepositoryItem("bfed9282-4c14-4956-9888-e20e00d441fc")]
            public virtual Ranorex.DivTag UEyeOl
            {
                get
                {
                    return _ueyeolInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl item info.
            /// </summary>
            [RepositoryItemInfo("bfed9282-4c14-4956-9888-e20e00d441fc")]
            public virtual RepoItemInfo UEyeOlInfo
            {
                get
                {
                    return _ueyeolInfo;
                }
            }

            /// <summary>
            /// The FlexFlex1QLayoutSocialLoginButton item.
            /// </summary>
            [RepositoryItem("2aa8960d-ca50-4be5-b842-1a244a0671fb")]
            public virtual Ranorex.DivTag FlexFlex1QLayoutSocialLoginButton
            {
                get
                {
                    return _flexflex1qlayoutsocialloginbuttonInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FlexFlex1QLayoutSocialLoginButton item info.
            /// </summary>
            [RepositoryItemInfo("2aa8960d-ca50-4be5-b842-1a244a0671fb")]
            public virtual RepoItemInfo FlexFlex1QLayoutSocialLoginButtonInfo
            {
                get
                {
                    return _flexflex1qlayoutsocialloginbuttonInfo;
                }
            }

            /// <summary>
            /// The FlexFlex1QLayoutSocialLoginButton1 item.
            /// </summary>
            [RepositoryItem("aa0cd8db-03f2-4294-8559-edf19b685f61")]
            public virtual Ranorex.DivTag FlexFlex1QLayoutSocialLoginButton1
            {
                get
                {
                    return _flexflex1qlayoutsocialloginbutton1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FlexFlex1QLayoutSocialLoginButton1 item info.
            /// </summary>
            [RepositoryItemInfo("aa0cd8db-03f2-4294-8559-edf19b685f61")]
            public virtual RepoItemInfo FlexFlex1QLayoutSocialLoginButton1Info
            {
                get
                {
                    return _flexflex1qlayoutsocialloginbutton1Info;
                }
            }

            /// <summary>
            /// The GirişYap item.
            /// </summary>
            [RepositoryItem("56c68d7b-0bec-4491-9ceb-dd60db254b2e")]
            public virtual Ranorex.PTag GirişYap
            {
                get
                {
                    return _girişyapInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap item info.
            /// </summary>
            [RepositoryItemInfo("56c68d7b-0bec-4491-9ceb-dd60db254b2e")]
            public virtual RepoItemInfo GirişYapInfo
            {
                get
                {
                    return _girişyapInfo;
                }
            }

            /// <summary>
            /// The ButtonQButtonQButtonMediumQSecond item.
            /// </summary>
            [RepositoryItem("02bbde3e-ba19-418c-a5be-7a2398e16bfd")]
            public virtual Ranorex.ButtonTag ButtonQButtonQButtonMediumQSecond
            {
                get
                {
                    return _buttonqbuttonqbuttonmediumqsecondInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonQButtonQButtonMediumQSecond item info.
            /// </summary>
            [RepositoryItemInfo("02bbde3e-ba19-418c-a5be-7a2398e16bfd")]
            public virtual RepoItemInfo ButtonQButtonQButtonMediumQSecondInfo
            {
                get
                {
                    return _buttonqbuttonqbuttonmediumqsecondInfo;
                }
            }

            /// <summary>
            /// The ErrorBoxWrapper item.
            /// </summary>
            [RepositoryItem("bf36e58c-1ed0-4455-ab21-eab16f862515")]
            public virtual Ranorex.DivTag ErrorBoxWrapper
            {
                get
                {
                    return _errorboxwrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ErrorBoxWrapper item info.
            /// </summary>
            [RepositoryItemInfo("bf36e58c-1ed0-4455-ab21-eab16f862515")]
            public virtual ErrorBoxWrapperInfoClass ErrorBoxWrapperInfo
            {
                get
                {
                    return _errorboxwrapperInfo;
                }
            }

            /// <summary>
            /// The RegisterEmail item.
            /// </summary>
            [RepositoryItem("0e790ea7-3706-478f-a88a-f21a46400003")]
            public virtual Ranorex.InputTag RegisterEmail
            {
                get
                {
                    return _registeremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterEmail item info.
            /// </summary>
            [RepositoryItemInfo("0e790ea7-3706-478f-a88a-f21a46400003")]
            public virtual RepoItemInfo RegisterEmailInfo
            {
                get
                {
                    return _registeremailInfo;
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item.
            /// </summary>
            [RepositoryItem("2f88602c-8480-4c22-a188-4894233d73ed")]
            public virtual Ranorex.InputTag RegisterPasswordInput
            {
                get
                {
                    return _registerpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("2f88602c-8480-4c22-a188-4894233d73ed")]
            public virtual RepoItemInfo RegisterPasswordInputInfo
            {
                get
                {
                    return _registerpasswordinputInfo;
                }
            }

            /// <summary>
            /// The EPostaVeŞifreniziGiriniz item.
            /// </summary>
            [RepositoryItem("e7044e87-7ef7-4105-91f3-62e798ccc2b6")]
            public virtual Ranorex.SpanTag EPostaVeŞifreniziGiriniz
            {
                get
                {
                    return _epostaveşifrenizigirinizInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The EPostaVeŞifreniziGiriniz item info.
            /// </summary>
            [RepositoryItemInfo("e7044e87-7ef7-4105-91f3-62e798ccc2b6")]
            public virtual RepoItemInfo EPostaVeŞifreniziGirinizInfo
            {
                get
                {
                    return _epostaveşifrenizigirinizInfo;
                }
            }

            /// <summary>
            /// The LuetfenGecerliBirEmailAdresiGiriniz item.
            /// </summary>
            [RepositoryItem("eac2fc1f-5fd0-4b63-8591-dc98f8652c72")]
            public virtual Ranorex.SpanTag LuetfenGecerliBirEmailAdresiGiriniz
            {
                get
                {
                    return _luetfengecerlibiremailadresigirinizInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The LuetfenGecerliBirEmailAdresiGiriniz item info.
            /// </summary>
            [RepositoryItemInfo("eac2fc1f-5fd0-4b63-8591-dc98f8652c72")]
            public virtual RepoItemInfo LuetfenGecerliBirEmailAdresiGirinizInfo
            {
                get
                {
                    return _luetfengecerlibiremailadresigirinizInfo;
                }
            }

            /// <summary>
            /// The LoginPasswordInput item.
            /// </summary>
            [RepositoryItem("d770c39c-2eb7-4f77-99de-b548bd346eb1")]
            public virtual Ranorex.InputTag LoginPasswordInput
            {
                get
                {
                    return _loginpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("d770c39c-2eb7-4f77-99de-b548bd346eb1")]
            public virtual RepoItemInfo LoginPasswordInputInfo
            {
                get
                {
                    return _loginpasswordinputInfo;
                }
            }

            /// <summary>
            /// The GirişYap1 item.
            /// </summary>
            [RepositoryItem("a4f19d55-db5e-41d5-bd0a-dea7713fbdc4")]
            public virtual Ranorex.SpanTag GirişYap1
            {
                get
                {
                    return _girişyap1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap1 item info.
            /// </summary>
            [RepositoryItemInfo("a4f19d55-db5e-41d5-bd0a-dea7713fbdc4")]
            public virtual RepoItemInfo GirişYap1Info
            {
                get
                {
                    return _girişyap1Info;
                }
            }

            /// <summary>
            /// The UEyeOl1 item.
            /// </summary>
            [RepositoryItem("abb9087b-cc3f-4f4b-98e2-5309fa131b96")]
            public virtual Ranorex.SpanTag UEyeOl1
            {
                get
                {
                    return _ueyeol1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl1 item info.
            /// </summary>
            [RepositoryItemInfo("abb9087b-cc3f-4f4b-98e2-5309fa131b96")]
            public virtual RepoItemInfo UEyeOl1Info
            {
                get
                {
                    return _ueyeol1Info;
                }
            }

            /// <summary>
            /// The UEyeOl2 item.
            /// </summary>
            [RepositoryItem("0276f16e-9809-4748-adc3-72808937c0d5")]
            public virtual Ranorex.SpanTag UEyeOl2
            {
                get
                {
                    return _ueyeol2Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl2 item info.
            /// </summary>
            [RepositoryItemInfo("0276f16e-9809-4748-adc3-72808937c0d5")]
            public virtual RepoItemInfo UEyeOl2Info
            {
                get
                {
                    return _ueyeol2Info;
                }
            }

            /// <summary>
            /// The CustomStampBoxWrapper item.
            /// </summary>
            [RepositoryItem("d2fb041f-c76a-4dd6-ae8b-11cfd1c6c53e")]
            public virtual Ranorex.DivTag CustomStampBoxWrapper
            {
                get
                {
                    return _customstampboxwrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CustomStampBoxWrapper item info.
            /// </summary>
            [RepositoryItemInfo("d2fb041f-c76a-4dd6-ae8b-11cfd1c6c53e")]
            public virtual RepoItemInfo CustomStampBoxWrapperInfo
            {
                get
                {
                    return _customstampboxwrapperInfo;
                }
            }

            /// <summary>
            /// The CustomStampBoxWrapper1 item.
            /// </summary>
            [RepositoryItem("161a32fb-cd11-4c7a-9716-2739d10f3f5d")]
            public virtual Ranorex.DivTag CustomStampBoxWrapper1
            {
                get
                {
                    return _customstampboxwrapper1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CustomStampBoxWrapper1 item info.
            /// </summary>
            [RepositoryItemInfo("161a32fb-cd11-4c7a-9716-2739d10f3f5d")]
            public virtual RepoItemInfo CustomStampBoxWrapper1Info
            {
                get
                {
                    return _customstampboxwrapper1Info;
                }
            }

            /// <summary>
            /// The DivTag5750TL item.
            /// </summary>
            [RepositoryItem("816fec75-dca5-43b7-8ab2-fcee14df90fa")]
            public virtual Ranorex.DivTag DivTag5750TL
            {
                get
                {
                    return _divtag5750tlInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTag5750TL item info.
            /// </summary>
            [RepositoryItemInfo("816fec75-dca5-43b7-8ab2-fcee14df90fa")]
            public virtual RepoItemInfo DivTag5750TLInfo
            {
                get
                {
                    return _divtag5750tlInfo;
                }
            }

            /// <summary>
            /// The SomeDivTag item.
            /// </summary>
            [RepositoryItem("81285153-15e9-44cb-b070-a6e215cb38de")]
            public virtual Ranorex.DivTag SomeDivTag
            {
                get
                {
                    return _somedivtagInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SomeDivTag item info.
            /// </summary>
            [RepositoryItemInfo("81285153-15e9-44cb-b070-a6e215cb38de")]
            public virtual RepoItemInfo SomeDivTagInfo
            {
                get
                {
                    return _somedivtagInfo;
                }
            }

            /// <summary>
            /// The SepeteEkle item.
            /// </summary>
            [RepositoryItem("dc8bff9e-a44b-448c-a4c9-39459bb99711")]
            public virtual Ranorex.DivTag SepeteEkle
            {
                get
                {
                    return _sepeteekleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle item info.
            /// </summary>
            [RepositoryItemInfo("dc8bff9e-a44b-448c-a4c9-39459bb99711")]
            public virtual RepoItemInfo SepeteEkleInfo
            {
                get
                {
                    return _sepeteekleInfo;
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComSepet item.
            /// </summary>
            [RepositoryItem("fd03de0d-9e25-457f-8c33-e1dae0d017a1")]
            public virtual Ranorex.ATag HttpsWwwTrendyolComSepet
            {
                get
                {
                    return _httpswwwtrendyolcomsepetInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComSepet item info.
            /// </summary>
            [RepositoryItemInfo("fd03de0d-9e25-457f-8c33-e1dae0d017a1")]
            public virtual RepoItemInfo HttpsWwwTrendyolComSepetInfo
            {
                get
                {
                    return _httpswwwtrendyolcomsepetInfo;
                }
            }

            /// <summary>
            /// The IHeart item.
            /// </summary>
            [RepositoryItem("6ee7c8f0-7114-4f28-8568-578c6c6c4532")]
            public virtual Ranorex.ITag IHeart
            {
                get
                {
                    return _iheartInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IHeart item info.
            /// </summary>
            [RepositoryItemInfo("6ee7c8f0-7114-4f28-8568-578c6c6c4532")]
            public virtual RepoItemInfo IHeartInfo
            {
                get
                {
                    return _iheartInfo;
                }
            }

            /// <summary>
            /// The Favorilerim item.
            /// </summary>
            [RepositoryItem("25869f25-39b7-490e-ad31-4457ca968de0")]
            public virtual Ranorex.PTag Favorilerim
            {
                get
                {
                    return _favorilerimInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Favorilerim item info.
            /// </summary>
            [RepositoryItemInfo("25869f25-39b7-490e-ad31-4457ca968de0")]
            public virtual RepoItemInfo FavorilerimInfo
            {
                get
                {
                    return _favorilerimInfo;
                }
            }

            /// <summary>
            /// The Sepetim item.
            /// </summary>
            [RepositoryItem("14b26e46-3f5b-42ea-a360-7ba6b2b6fd44")]
            public virtual Ranorex.PTag Sepetim
            {
                get
                {
                    return _sepetimInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Sepetim item info.
            /// </summary>
            [RepositoryItemInfo("14b26e46-3f5b-42ea-a360-7ba6b2b6fd44")]
            public virtual RepoItemInfo SepetimInfo
            {
                get
                {
                    return _sepetimInfo;
                }
            }

            /// <summary>
            /// The SepetiOnayla item.
            /// </summary>
            [RepositoryItem("21d6696c-5842-4caf-a748-eaf69d5be624")]
            public virtual Ranorex.SpanTag SepetiOnayla
            {
                get
                {
                    return _sepetionaylaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SepetiOnayla item info.
            /// </summary>
            [RepositoryItemInfo("21d6696c-5842-4caf-a748-eaf69d5be624")]
            public virtual RepoItemInfo SepetiOnaylaInfo
            {
                get
                {
                    return _sepetionaylaInfo;
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComSepetimOdeme item.
            /// </summary>
            [RepositoryItem("5816910f-baee-4af8-9db0-8ad3cb7b4050")]
            public virtual Ranorex.ATag HttpsWwwTrendyolComSepetimOdeme
            {
                get
                {
                    return _httpswwwtrendyolcomsepetimodemeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComSepetimOdeme item info.
            /// </summary>
            [RepositoryItemInfo("5816910f-baee-4af8-9db0-8ad3cb7b4050")]
            public virtual RepoItemInfo HttpsWwwTrendyolComSepetimOdemeInfo
            {
                get
                {
                    return _httpswwwtrendyolcomsepetimodemeInfo;
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComUyelikcbEqhttps folder.
            /// </summary>
            [RepositoryFolder("84c52d40-52f6-475b-b527-d71595420ce5")]
            public virtual Trendyol_Test_Automation_with_RanorexRepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsFolder HttpsWwwTrendyolComUyelikcbEqhttps
            {
                get { return _httpswwwtrendyolcomuyelikcbeqhttps; }
            }
        }

        /// <summary>
        /// The HttpsWwwTrendyolComUyelikcbEqhttpsFolder folder.
        /// </summary>
        [RepositoryFolder("84c52d40-52f6-475b-b527-d71595420ce5")]
        public partial class HttpsWwwTrendyolComUyelikcbEqhttpsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _qbuttonqbuttonmediumqfluidqprimaInfo;
            RepoItemInfo _emailinputqinputwrapperInfo;
            RepoItemInfo _qinputwrapperInfo;
            RepoItemInfo _flexflexcolumngenderInfo;
            RepoItemInfo _tycheckboxwrappertydisplayflexInfo;
            TyCheckboxWrapperTyDisplayFlex1InfoClass _tycheckboxwrappertydisplayflex1Info;
            RepoItemInfo _ueyeolInfo;
            RepoItemInfo _maleqbuttonqbuttonmediumqfluidqInfo;
            RepoItemInfo _tycheckInfo;
            RepoItemInfo _erkekInfo;
            RepoItemInfo _passwordwrapperInfo;

            /// <summary>
            /// Creates a new HttpsWwwTrendyolComUyelikcbEqhttps  folder.
            /// </summary>
            public HttpsWwwTrendyolComUyelikcbEqhttpsFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpsWwwTrendyolComUyelikcbEqhttps", ".//div[#'login-register']//form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']", parentFolder, 30000, null, false, "84c52d40-52f6-475b-b527-d71595420ce5", "")
            {
                _qbuttonqbuttonmediumqfluidqprimaInfo = new RepoItemInfo(this, "QButtonQButtonMediumQFluidQPrima", "button", "button", 30000, null, "5cc3ff65-2827-4b76-895a-d894ec0e4a2f");
                _emailinputqinputwrapperInfo = new RepoItemInfo(this, "EmailInputQInputWrapper", "div[1]", "div[1]", 30000, null, "0a5e2d90-dc0a-4685-b235-100e8aff081f");
                _qinputwrapperInfo = new RepoItemInfo(this, "QInputWrapper", "div[2]/?/?/div", "div[2]/div/div", 30000, null, "6466d698-91c6-4012-a2e7-d083d545fcad");
                _flexflexcolumngenderInfo = new RepoItemInfo(this, "FlexFlexColumnGender", "div[3]", "div[3]", 30000, null, "47d16d09-937d-4854-804e-475533ec8683");
                _tycheckboxwrappertydisplayflexInfo = new RepoItemInfo(this, "TyCheckboxWrapperTyDisplayFlex", "div[5]/div/div[1]", "div[5]/div/div[1]", 30000, null, "19ef9bd3-c732-46d1-b5e5-7cbba33db9e8");
                _tycheckboxwrappertydisplayflex1Info = new TyCheckboxWrapperTyDisplayFlex1InfoClass(this);
                _ueyeolInfo = new RepoItemInfo(this, "UEyeOl", "?/?/span[@innertext='Üye Ol']", "button/span[@innertext='Üye Ol']", 30000, null, "8432038b-cf24-40d6-85e6-7869fd2b11b9");
                _maleqbuttonqbuttonmediumqfluidqInfo = new RepoItemInfo(this, "MaleQButtonQButtonMediumQFluidQ", "div[3]/div/button[2]", "div[3]/div/button[2]", 30000, null, "306f0c3b-20b3-40c6-8d57-df8fd90edb08");
                _tycheckInfo = new RepoItemInfo(this, "TyCheck", "div[6]//svg", "div[1]/div/svg", 30000, null, "f7edd7a7-2b3d-4f41-a9a7-4c34e95722cc");
                _erkekInfo = new RepoItemInfo(this, "Erkek", "div[3]/div/button[2]/span[@innertext='Erkek']", "", 30000, null, "ff325f3d-8476-4f8e-981f-2b01603c619f");
                _passwordwrapperInfo = new RepoItemInfo(this, "PasswordWrapper", "div[2]", "div[2]", 30000, null, "ee03ec4e-a17a-449a-bfbb-a96100bcbf20");
            }

            /// <summary>
            /// The TyCheckboxWrapperTyDisplayFlex1InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("95af280f-10aa-4e0c-bd37-1d7f73509fc7")]
            public class TyCheckboxWrapperTyDisplayFlex1InfoClass : RepoItemInfo
            {
                /// <summary>
                /// TyCheckboxWrapperTyDisplayFlex1InfoClass class constructor.
                /// </summary>
                public TyCheckboxWrapperTyDisplayFlex1InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "TyCheckboxWrapperTyDisplayFlex1", "div[6]/div/div[1]", 30000, null, "95af280f-10aa-4e0c-bd37-1d7f73509fc7")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("2762c21a-5904-4e10-b171-87f5792e518a")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("2762c21a-5904-4e10-b171-87f5792e518a");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("2762c21a-5904-4e10-b171-87f5792e518a")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("2762c21a-5904-4e10-b171-87f5792e518a", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("84c52d40-52f6-475b-b527-d71595420ce5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("84c52d40-52f6-475b-b527-d71595420ce5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item.
            /// </summary>
            [RepositoryItem("5cc3ff65-2827-4b76-895a-d894ec0e4a2f")]
            public virtual Ranorex.ButtonTag QButtonQButtonMediumQFluidQPrima
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item info.
            /// </summary>
            [RepositoryItemInfo("5cc3ff65-2827-4b76-895a-d894ec0e4a2f")]
            public virtual RepoItemInfo QButtonQButtonMediumQFluidQPrimaInfo
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo;
                }
            }

            /// <summary>
            /// The EmailInputQInputWrapper item.
            /// </summary>
            [RepositoryItem("0a5e2d90-dc0a-4685-b235-100e8aff081f")]
            public virtual Ranorex.DivTag EmailInputQInputWrapper
            {
                get
                {
                    return _emailinputqinputwrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The EmailInputQInputWrapper item info.
            /// </summary>
            [RepositoryItemInfo("0a5e2d90-dc0a-4685-b235-100e8aff081f")]
            public virtual RepoItemInfo EmailInputQInputWrapperInfo
            {
                get
                {
                    return _emailinputqinputwrapperInfo;
                }
            }

            /// <summary>
            /// The QInputWrapper item.
            /// </summary>
            [RepositoryItem("6466d698-91c6-4012-a2e7-d083d545fcad")]
            public virtual Ranorex.DivTag QInputWrapper
            {
                get
                {
                    return _qinputwrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The QInputWrapper item info.
            /// </summary>
            [RepositoryItemInfo("6466d698-91c6-4012-a2e7-d083d545fcad")]
            public virtual RepoItemInfo QInputWrapperInfo
            {
                get
                {
                    return _qinputwrapperInfo;
                }
            }

            /// <summary>
            /// The FlexFlexColumnGender item.
            /// </summary>
            [RepositoryItem("47d16d09-937d-4854-804e-475533ec8683")]
            public virtual Ranorex.DivTag FlexFlexColumnGender
            {
                get
                {
                    return _flexflexcolumngenderInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FlexFlexColumnGender item info.
            /// </summary>
            [RepositoryItemInfo("47d16d09-937d-4854-804e-475533ec8683")]
            public virtual RepoItemInfo FlexFlexColumnGenderInfo
            {
                get
                {
                    return _flexflexcolumngenderInfo;
                }
            }

            /// <summary>
            /// The TyCheckboxWrapperTyDisplayFlex item.
            /// </summary>
            [RepositoryItem("19ef9bd3-c732-46d1-b5e5-7cbba33db9e8")]
            public virtual Ranorex.DivTag TyCheckboxWrapperTyDisplayFlex
            {
                get
                {
                    return _tycheckboxwrappertydisplayflexInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The TyCheckboxWrapperTyDisplayFlex item info.
            /// </summary>
            [RepositoryItemInfo("19ef9bd3-c732-46d1-b5e5-7cbba33db9e8")]
            public virtual RepoItemInfo TyCheckboxWrapperTyDisplayFlexInfo
            {
                get
                {
                    return _tycheckboxwrappertydisplayflexInfo;
                }
            }

            /// <summary>
            /// The TyCheckboxWrapperTyDisplayFlex1 item.
            /// </summary>
            [RepositoryItem("95af280f-10aa-4e0c-bd37-1d7f73509fc7")]
            public virtual Ranorex.DivTag TyCheckboxWrapperTyDisplayFlex1
            {
                get
                {
                    return _tycheckboxwrappertydisplayflex1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The TyCheckboxWrapperTyDisplayFlex1 item info.
            /// </summary>
            [RepositoryItemInfo("95af280f-10aa-4e0c-bd37-1d7f73509fc7")]
            public virtual TyCheckboxWrapperTyDisplayFlex1InfoClass TyCheckboxWrapperTyDisplayFlex1Info
            {
                get
                {
                    return _tycheckboxwrappertydisplayflex1Info;
                }
            }

            /// <summary>
            /// The UEyeOl item.
            /// </summary>
            [RepositoryItem("8432038b-cf24-40d6-85e6-7869fd2b11b9")]
            public virtual Ranorex.SpanTag UEyeOl
            {
                get
                {
                    return _ueyeolInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl item info.
            /// </summary>
            [RepositoryItemInfo("8432038b-cf24-40d6-85e6-7869fd2b11b9")]
            public virtual RepoItemInfo UEyeOlInfo
            {
                get
                {
                    return _ueyeolInfo;
                }
            }

            /// <summary>
            /// The MaleQButtonQButtonMediumQFluidQ item.
            /// </summary>
            [RepositoryItem("306f0c3b-20b3-40c6-8d57-df8fd90edb08")]
            public virtual Ranorex.ButtonTag MaleQButtonQButtonMediumQFluidQ
            {
                get
                {
                    return _maleqbuttonqbuttonmediumqfluidqInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The MaleQButtonQButtonMediumQFluidQ item info.
            /// </summary>
            [RepositoryItemInfo("306f0c3b-20b3-40c6-8d57-df8fd90edb08")]
            public virtual RepoItemInfo MaleQButtonQButtonMediumQFluidQInfo
            {
                get
                {
                    return _maleqbuttonqbuttonmediumqfluidqInfo;
                }
            }

            /// <summary>
            /// The TyCheck item.
            /// </summary>
            [RepositoryItem("f7edd7a7-2b3d-4f41-a9a7-4c34e95722cc")]
            public virtual Ranorex.SvgTag TyCheck
            {
                get
                {
                    return _tycheckInfo.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The TyCheck item info.
            /// </summary>
            [RepositoryItemInfo("f7edd7a7-2b3d-4f41-a9a7-4c34e95722cc")]
            public virtual RepoItemInfo TyCheckInfo
            {
                get
                {
                    return _tycheckInfo;
                }
            }

            /// <summary>
            /// The Erkek item.
            /// </summary>
            [RepositoryItem("ff325f3d-8476-4f8e-981f-2b01603c619f")]
            public virtual Ranorex.SpanTag Erkek
            {
                get
                {
                    return _erkekInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Erkek item info.
            /// </summary>
            [RepositoryItemInfo("ff325f3d-8476-4f8e-981f-2b01603c619f")]
            public virtual RepoItemInfo ErkekInfo
            {
                get
                {
                    return _erkekInfo;
                }
            }

            /// <summary>
            /// The PasswordWrapper item.
            /// </summary>
            [RepositoryItem("ee03ec4e-a17a-449a-bfbb-a96100bcbf20")]
            public virtual Ranorex.DivTag PasswordWrapper
            {
                get
                {
                    return _passwordwrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PasswordWrapper item info.
            /// </summary>
            [RepositoryItemInfo("ee03ec4e-a17a-449a-bfbb-a96100bcbf20")]
            public virtual RepoItemInfo PasswordWrapperInfo
            {
                get
                {
                    return _passwordwrapperInfo;
                }
            }
        }

        /// <summary>
        /// The SepetimTrendyolGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("526bc77a-1dc7-4a3d-8fb3-d10fe773818e")]
        public partial class SepetimTrendyolGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _backInfo;

            /// <summary>
            /// Creates a new SepetimTrendyolGoogleChrome  folder.
            /// </summary>
            public SepetimTrendyolGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SepetimTrendyolGoogleChrome", "/form[@title>'Sepetim - Trendyol - Google']", parentFolder, 30000, null, true, "526bc77a-1dc7-4a3d-8fb3-d10fe773818e", "")
            {
                _backInfo = new RepoItemInfo(this, "Back", "container[@accessiblename>'Sepetim - Trendyol - Google']/container[@accessiblename='Google Chrome']/container/container[2]/container[1]/toolbar[1]/button[@accessiblename='Back']", ".//button[@accessiblename='Back']", 30000, null, "b4bb958a-547d-41c5-b3e0-5013f24dcb8c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("526bc77a-1dc7-4a3d-8fb3-d10fe773818e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("526bc77a-1dc7-4a3d-8fb3-d10fe773818e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Back item.
            /// </summary>
            [RepositoryItem("b4bb958a-547d-41c5-b3e0-5013f24dcb8c")]
            public virtual Ranorex.Button Back
            {
                get
                {
                    return _backInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Back item info.
            /// </summary>
            [RepositoryItemInfo("b4bb958a-547d-41c5-b3e0-5013f24dcb8c")]
            public virtual RepoItemInfo BackInfo
            {
                get
                {
                    return _backInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
